# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configura
client_id = "a1ab97a46b1da2e22ae82de7c621e32a"
application_url = "https://your-app-url.com"
embedded = true
name = "Rabbi COuntry Blocker"
handle = "insta-18"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
dev_store_url = "newStorewdce.myshopify.com"

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# Use read_products as a default for the app scope
scopes = "write_products,read_products"

[auth]
redirect_urls = [
    "https://your-app-url.com/auth/callback",
    "https://your-app-url.com/auth/shopify/callback",
    "https://your-app-url.com/auth/tokens"
]

[pos]
embedded = false

[env]
SHOPIFY_API_KEY = "YOUR_API_KEY"
SHOPIFY_API_SECRET = "YOUR_API_SECRET"
SCOPES = "write_products,read_products"
HOST = "https://your-app-url.com"
