# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a1ab97a46b1da2e22ae82de7c621e32a"
application_url = "https://participants-shipments-decent-trains.trycloudflare.com"
embedded = true
name = "Insta"
handle = "insta-18"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://participants-shipments-decent-trains.trycloudflare.com/auth/callback",
  "https://participants-shipments-decent-trains.trycloudflare.com/auth/shopify/callback",
  "https://participants-shipments-decent-trains.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
