name = "Country Blocker"
client_id = "YOUR_CLIENT_ID"
application_url = "YOUR_APP_URL"
embedded = true

[access_scopes]
# Use scopes for your app
scopes = "write_products,write_customers,write_orders"

[auth]
redirect_urls = [
    "YOUR_APP_URL/auth/callback",
    "YOUR_APP_URL/auth/shopify/callback",
    "YOUR_APP_URL/api/auth/callback",
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "YOUR_DEV_STORE_URL"

[env]
SHOPIFY_API_KEY = "YOUR_API_KEY"
SHOPIFY_API_SECRET = "YOUR_API_SECRET"
SCOPES = "write_products,write_customers,write_orders"
HOST = "YOUR_APP_URL" 